/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado;

import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Antonio
 */
public class Ahorcado1 extends javax.swing.JFrame {

    String letter;
    String palabra;
    String palabraVacia = "";
    char[] palabraCambia;
    int fallos;
    char letra;
    private static final Logger LOGGER = Logger.getLogger(Ahorcado1.class.getName());

    public Ahorcado1() {
        initComponents();
         setIconImage(new ImageIcon(getClass().getResource("/imagenes/ahorcado.png"))
                .getImage());
        this.setTitle("Ahorcado");
        this.setLocationRelativeTo(null);
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelIntroduzca = new javax.swing.JLabel();
        jButtonComprobar = new javax.swing.JButton();
        jTextFieldIntroducirLetra = new javax.swing.JTextField();
        jTextFieldIntroducirPalabra = new javax.swing.JTextField();
        jButtonJugar = new javax.swing.JButton();
        jLabelPalabraVariable = new javax.swing.JLabel();
        jLabelContadorFallos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelIntroduzca.setText("Introduzca");

        jButtonComprobar.setText("Comprobar");
        jButtonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprobarActionPerformed(evt);
            }
        });

        jButtonJugar.setText("JUGAR");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });

        jLabelPalabraVariable.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPalabraVariable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelContadorFallos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContadorFallos.setText("0");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Fallos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelPalabraVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelContadorFallos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIntroducirPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonJugar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextFieldIntroducirLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelIntroduzca, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonComprobar))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIntroducirPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonJugar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabelIntroduzca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIntroducirLetra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonComprobar)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelPalabraVariable, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelContadorFallos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprobarActionPerformed
        letter = jTextFieldIntroducirLetra.getText().trim();
        try {
            letra = letter.charAt(0);
        } catch (IndexOutOfBoundsException ex) {
            LOGGER.warning("No se ha introducido una letra: " + ex.toString());
            JOptionPane.showMessageDialog(this, "Debe introducir una letra",
                    "Ahorcado", JOptionPane.INFORMATION_MESSAGE);
        }
        try {
            for (int i = 0; i < palabra.length(); i++) {
                if (letra == palabra.charAt(i)) {
                    /*Convertimos el string palabraVacia en un array para conseguir 
                    que cada caracter este en una posición del array para poder 
                    modificarlo posteriormente*/
                    palabraCambia = palabraVacia.toCharArray();
                    /*En la posición de la palabra donde el caracter sea igual a la 
                    letra introducida,  asignamos la letra introducida, csmbiando 
                    el _ por la letra introducida*/
                    palabraCambia[i] = letra;
                    /*Como palabraCambia es un array de caracteres, cambiamos el tipo 
                    de dato a string*/
                    palabraVacia = String.valueOf(palabraCambia);
                }
            }
        } catch (NullPointerException e) {
            LOGGER.warning("No se ha introducido una palabra: " + e.toString());
            JOptionPane.showMessageDialog(this, "Debe introducir una palabra",
                    "Ahorcado", JOptionPane.INFORMATION_MESSAGE);
        }
        if (palabra.contains(letter) == false) {
                fallos++;
            /*Si la letra que introducimos no coincide con ninguna de las letras 
            de la palabras el contador de fallos aumentará*/
        }
        jLabelContadorFallos.setText(String.valueOf(fallos));
        jLabelPalabraVariable.setText(palabraVacia);
        jTextArea1.append(letra + " ");
        jTextFieldIntroducirLetra.setText("");
        if (fallos == 6) {
            jTextFieldIntroducirLetra.setEditable(false);
            jButtonComprobar.setEnabled(false);
            jTextArea1.setText("");
            jLabelPalabraVariable.setText ("");
            fallos = 0;
            jLabelContadorFallos.setText(String.valueOf(fallos));
            JOptionPane.showMessageDialog(this, "Has perdido", "Ahorcado",
                    JOptionPane.INFORMATION_MESSAGE);
            /*Una vez que los fallos lleguen a 6 el jugador pierde y reseteamos 
            los campos y el contador de fallos*/
        }
        if (palabraVacia.contains ("_") == false){
            jTextFieldIntroducirLetra.setEditable(false);
            jButtonComprobar.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Has ganado", "Ahorcado",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonComprobarActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        jTextFieldIntroducirLetra.setEditable(true);
        jButtonComprobar.setEnabled(true);
        palabraVacia = "";
        fallos = 0;
        jLabelContadorFallos.setText(String.valueOf(fallos));
        palabra = jTextFieldIntroducirPalabra.getText();
        jTextFieldIntroducirPalabra.setText("");
        for (int i = 0; i < palabra.length(); i++) {
            palabraVacia += "_";
        }
        jLabelPalabraVariable.setText(palabraVacia);
        jTextArea1.setText("");
    }//GEN-LAST:event_jButtonJugarActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprobar;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelContadorFallos;
    private javax.swing.JLabel jLabelIntroduzca;
    private javax.swing.JLabel jLabelPalabraVariable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldIntroducirLetra;
    private javax.swing.JTextField jTextFieldIntroducirPalabra;
    // End of variables declaration//GEN-END:variables
}
